export const CFG = {
  bride: "Disha",
  groom: "Devanshu",
  date: "2026-11-20T18:00:00+05:30",
  dateText: "20 · 11 · 2026",
  quote: "Two souls, one journey — bound by love, blessed by tradition.",
  brideInfo: "Daughter of Mr. & Mrs. Sharma. A dreamer with a heart full of poetry.",
  groomInfo: "Son of Mr. & Mrs. Malhotra. A gentle soul with a love for music.",
  bridePhoto: "",
  groomPhoto: "",
  venue: "The Royal Haveli",
  address: "Lake Pichola Road, Udaipur, Rajasthan 313001",
  venueImg: "",
  events: [
    { n: "Haldi",     i: "🌼", d: "16 Feb 2027", t: "11:00 AM", v: "Haveli Courtyard",  x: "Turmeric, laughter and golden blessings." },
    { n: "Mehendi",   i: "🌿", d: "16 Feb 2027", t: "4:00 PM",  v: "Garden Terrace",    x: "Intricate henna, folk songs and sweet stories." },
    { n: "Sangeet",   i: "🪘", d: "17 Feb 2027", t: "7:00 PM",  v: "Grand Ballroom",    x: "A night of music, dance and dhol beats." },
    { n: "Wedding",   i: "🔥", d: "18 Feb 2027", t: "6:00 PM",  v: "Lakeside Mandap",   x: "Pheras around the sacred fire, under the stars." },
    { n: "Reception", i: "🥂", d: "19 Feb 2027", t: "8:00 PM",  v: "Royal Durbar Hall", x: "An evening of feasting and celebration." },
  ],
  story: [
    ["The Beginning",      "2019",         "Two strangers, one city, and a universe quietly planning."],
    ["First Meeting",      "Jan 2020",     "A rainy café, a shared umbrella, a smile that stayed."],
    ["First Conversation", "Feb 2020",     "Hours felt like minutes; we never ran out of words."],
    ["Our Journey",        "2020 – 2025",  "Laughter, distance, growth — and a love that deepened."],
    ["The Proposal",       "Dec 2025",     "Under a sky of lanterns, she said yes."],
    ["Forever Begins",     "18 Feb 2027",  "Seven pheras, seven promises, one lifetime."],
  ],
  brideFam: [
    "Mr. Rajesh Sharma",
    "Mrs. Sunita Sharma",
    "Grandparents: Late Sh. Mohan Lal Sharma & Smt. Kamla Devi",
  ],
  groomFam: [
    "Mr. Anil Malhotra",
    "Mrs. Meera Malhotra",
    "Grandparents: Sh. Harish Malhotra & Smt. Leela Devi",
  ],
  gallery: [
    { src: "", r: 1.3 },
    { src: "", r: 0.8 },
    { src: "", r: 1 },
    { src: "", r: 1.5 },
    { src: "", r: 0.9 },
    { src: "", r: 1.2 },
  ],
  wishes: [
    ["Nani ji", "May your life be filled with endless love and joy."],
    ["Riya",    "Two beautiful souls, one beautiful journey. Congratulations!"],
  ],
};